sudo: false
language: node_js
node_js:
  - "stable"
  - "4.2"
script:
  - npm run build
  - npm test
after_script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coveragen
