sudo: false
language: node_js
node_js:
  - "stable"
  - "4.2"
before_script:
  - npm install -g gulp
  - npm install
script:
  - npm run build
  - npm test
after_script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
