// Generated by CoffeeScript 1.10.0
(function() {
  var postcss, preref;

  postcss = require('postcss');

  preref = postcss.plugin('postcss-preref', function(opts) {
    if (opts == null) {
      opts = {
        token: '-'
      };
    }
    return function(css) {
      var ref;
      ref = null;
      return css.walkRules(function(rule) {
        var i, len, ref1, result, selector;
        if (/^&/.test(rule.selector)) {
          result = [];
          ref1 = ref.split(/,/);
          for (i = 0, len = ref1.length; i < len; i++) {
            selector = ref1[i];
            result.push(rule.selector.replace(/&/, selector));
          }
          return rule.selector = result.join(",");
        } else {
          return ref = rule.selector;
        }
      });
    };
  });

  module.exports = preref;

}).call(this);
